version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mdex-bot-db
      POSTGRES_USER: mdex-bot
      POSTGRES_PASSWORD: pwd123
    ports:
      - 5432:5432
